language: cpp
before_install:
  - sudo apt update
  - sudo apt install snapd
install:
  - sudo snap install powershell --classic
script:
  - pwsh -File build.ps1
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  repo: koyokr/sjb-init
  target-branch: gh-pages
  committer-from-gh: true
  on:
    branch: master
