language: generic

os: osx
osx_image: xcode9.1
install:
  - brew update
  - brew tap caskroom/cask
  - brew cask install powershell

script:
  - pwsh -File build.ps1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  repo: koyokr/sjb-init
  target-branch: gh-pages
  committer-from-gh: true
  on:
    branch: master
